// Generated by https://quicktype.io

export interface BookProps {
  id?: string;
  name: string;
  description: string;
  genre?: Genre;
  coverUrl: string;
  averageRating: number;
  haveRead: number;
  currentlyReading: number;
  wantToRead: number;
}

export enum Genre {
  Business = "Business",
  Programming = "Programming",
}
export type Option = {
  value: string;
  label: string;
};
